/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.villalem.reservations;

import static gestionagenda.GestionAgenda.rq;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alexis
 */
public class PanelAgenda extends javax.swing.JPanel {
    
    private ArrayList<Evenement> ListeEvenements = new ArrayList<>();
    private Calendar cal = Calendar.getInstance();
    /**
     * Creates new form PanelAgenda
     */
    public PanelAgenda() {
        initComponents();
        remplirTableau(cal);
    }
    
    private void remplirTableau(Calendar c) {
      Calendar cal2 = (Calendar)c.clone();
      cal2.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);//met le calendrier à Lundi
      for (int i=0;i<7;i++) {
          ResultSet rs;
          try {
              rs = rq.getReservationsJour(cal2);

            try {
                  while(rs.next()) {
                      String dtDebut = new String();
                      String dtFin = new String();
                      dtDebut = rs.getObject("dateDebut").toString().substring(11,13);
                      dtFin = rs.getObject("dateFin").toString().substring(11,13);
                      int dtDebutInt = Integer.parseInt(dtDebut);
                      int dtFinInt = Integer.parseInt(dtFin);
                      System.out.println( (dtFinInt-6)*30 );
                      ListeEvenements.add(new Evenement(40+i*120, (dtDebutInt-6)*30, 60, (dtFinInt-dtDebutInt)*30));
                  }
              } catch (SQLException ex) {
                  Logger.getLogger(PanelAgenda.class.getName()).log(Level.SEVERE, null, ex);
              }
                      } catch (SQLException ex) {
                  Logger.getLogger(PanelAgenda.class.getName()).log(Level.SEVERE, null, ex);
              }
        cal2.add(Calendar.DATE, 1);
      }
      
  }
    
    public void paintComponent(Graphics g) {
    //cette méthode construit l'arrière plan de l'agenda, avec une colonne par jour de la semaine
    setBackground(Color.white);
    this.repaint();
    //Antialiasing pour lisser les chiffres et lettres éventuels:
    ((Graphics2D) g).setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
    int hauteurFenetre = this.getHeight();
    g.drawRect(0, 0, 40, hauteurFenetre);//première colonne où on placera les heures de 7 à 23h
    for(int i=7; i<24; i++) { //affiche l'heure de 7 à 23h
        String heure = Integer.toString(i);
        g.drawString(heure + ":00", 0, (i-6)*30);//une heure = 30px
    }
    for(int i=0; i<7; i++) { //affiche une colonne pour chaque jour de la semaine
        g.drawRect(i*120+40, 0, 120, hauteurFenetre);
    }
    for (Evenement s : ListeEvenements) {
        s.draw(g);
    }
    
  } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
