/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.villalem.admin;

import static gestionagenda.GestionAgenda.rq;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author avigaelle
 */
public class ITcreerReservation extends javax.swing.JFrame {

    /**
     * Creates new form ITcreerReservation
     */
    public ITcreerReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnnuler = new javax.swing.JButton();
        btnFormule = new javax.swing.JButton();
        btnNombrePersonnes = new javax.swing.JButton();
        btnNombreHeures = new javax.swing.JButton();
        btnSalleDisposition = new javax.swing.JButton();
        btnHeureDebut = new javax.swing.JButton();
        btnClient = new javax.swing.JButton();
        btnHeureFin = new javax.swing.JButton();
        btnDateFin = new javax.swing.JButton();
        btnDateDebut = new javax.swing.JButton();
        btnOption = new javax.swing.JButton();
        btnService = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnFormule.setText("formule");

        btnNombrePersonnes.setText("nombre de personnes");

        btnNombreHeures.setText("nombre d'heures");

        btnSalleDisposition.setText("salle et disposition");

        btnHeureDebut.setText("heure de debut");

        btnClient.setText("client");
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });

        btnHeureFin.setText("heure de fin");

        btnDateFin.setText("date de fin");

        btnDateDebut.setText("date de debut");

        btnOption.setText("option");

        btnService.setText("service");

        btnEnregistrer.setText("Enregistrer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNombreHeures, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalleDisposition, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFormule, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOption, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnService, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDateFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNombrePersonnes, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(btnDateDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHeureDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHeureFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClient, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnClient)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnService)
                    .addComponent(btnNombrePersonnes))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOption)
                    .addComponent(btnDateDebut))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormule)
                    .addComponent(btnDateFin))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalleDisposition)
                    .addComponent(btnHeureDebut))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNombreHeures)
                    .addComponent(btnHeureFin))
                .addGap(46, 46, 46)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        try {
            String[] etatClient = {"selectionner un client déjà existant", "créer un nouveau client"};
            String quelClient = (String)JOptionPane.showInputDialog(null, "Voulez vous selectionner un client déja existant ou en créer un nouveau?","Choisir un client",JOptionPane.QUESTION_MESSAGE, null,etatClient,etatClient[0]);
            if ("selectionner un client déjà existant".equals(quelClient)){
                String[] clients;

                clients = rq.getClients();

                String[] noms = rq.getnomsClients();
                String[] prenoms = rq.getprenomsClients();
                String client = "";
                client = (String)JOptionPane.showInputDialog(null, "Veuillez sélectionner un client déjà existant","Selectionner un client",JOptionPane.QUESTION_MESSAGE, null,clients,clients[0]);
                if (client!=null){
                    int longueur = noms.length;
                    String[] client2 = new String[longueur];
                    String leNom = "";
                    String lePrenom = "";
                    for(int i = 0; i<longueur; i++){
                        client2[i] = prenoms[i]+" "+noms[i];
                        if(client2[i] == null ? client == null : client2[i].equals(client)){
                            leNom = noms[i];
                            lePrenom = prenoms[i];
                        }
                    }
                }
            }
            else{
                String nom = (String)JOptionPane.showInputDialog(null, "Entrez le nom du nouveau client","Nom client",JOptionPane.QUESTION_MESSAGE);
                if (!"".equals(nom)){
                    String prenom = (String)JOptionPane.showInputDialog(null, "Entrez le prenom du nouveau client","Prenom client",JOptionPane.QUESTION_MESSAGE);
                    if (!"".equals(prenom)){
                        String adresse = (String)JOptionPane.showInputDialog(null, "Entrez l'adresse du nouveau client","Adresse client",JOptionPane.QUESTION_MESSAGE);
                        if (!"".equals(adresse)){
                            String[] entitetab ={"entreprise", "association", "particulier"};
                            String entite = (String)JOptionPane.showInputDialog(null, "Quelle est l'entité du client","Entite client",JOptionPane.QUESTION_MESSAGE, null, entitetab, entitetab[0]);
                            if (entite!=null){
                                String eMail = (String)JOptionPane.showInputDialog(null, "Entrez le mail du client","Mail client",JOptionPane.QUESTION_MESSAGE);
                                JOptionPane.showMessageDialog(null, "Etes vous sur de vouloir créer un nouveau client avec les informations fournies","Nouveau client",JOptionPane.INFORMATION_MESSAGE);

                            }

                        }

                    }
                }
            }

        }catch (SQLException ex) {
            Logger.getLogger(ITcreerReservation.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITcreerReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITcreerReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITcreerReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITcreerReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITcreerReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnDateDebut;
    private javax.swing.JButton btnDateFin;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnFormule;
    private javax.swing.JButton btnHeureDebut;
    private javax.swing.JButton btnHeureFin;
    private javax.swing.JButton btnNombreHeures;
    private javax.swing.JButton btnNombrePersonnes;
    private javax.swing.JButton btnOption;
    private javax.swing.JButton btnSalleDisposition;
    private javax.swing.JButton btnService;
    // End of variables declaration//GEN-END:variables
}
