/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.villalem.reservations;

import static gestionagenda.GestionAgenda.rq;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexis
 */
public class TestTableau extends javax.swing.JFrame {

    /**
     * Creates new form TestTableau
     */
    public TestTableau() throws SQLException {
        initComponents();
        Calendar cal = Calendar.getInstance();
        remplirTableau(cal);
        jLabel1.setText(cal.getTime().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGauche = new javax.swing.JButton();
        btnDroite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnGauche.setText("<");
        btnGauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaucheActionPerformed(evt);
            }
        });

        btnDroite.setText(">");
        btnDroite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDroiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGauche, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDroite, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGauche)
                    .addComponent(btnDroite)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Calendar c = Calendar.getInstance();
    private void btnGaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaucheActionPerformed
        c.add(c.DAY_OF_YEAR, -7);
        try {
            remplirTableau(c);
        } catch (SQLException ex) {
            Logger.getLogger(TestTableau.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText(c.getTime().toString());
        //System.out.println(c.getTime());
    }//GEN-LAST:event_btnGaucheActionPerformed

    private void btnDroiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDroiteActionPerformed
        c.add(c.DAY_OF_YEAR, 7);
        try {
            remplirTableau(c);
        } catch (SQLException ex) {
            Logger.getLogger(TestTableau.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText(c.getTime().toString());
        //System.out.println(c.getTime());
    }//GEN-LAST:event_btnDroiteActionPerformed

    
    private void remplirTableau(Calendar cal) throws SQLException {
        Calendar cal2 = (Calendar)cal.clone();
        ResultSet rs = rq.getReservationsSemaine(cal2);
        try {
            while(jTable1.getRowCount() > 0) //retire les lignes du tableau, s'il y en a
            {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }
            int columns = rs.getMetaData().getColumnCount(); //obtient le nombre de colonnes dans le ResultSet
            while(rs.next()) //pour chaque ligne du ResultSet:
            {  
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++)
                {  
                    row[i - 1] = rs.getObject(i);
                }
                //insert la ligne de résultat dans le tableau:
                ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow()-1,row);
            }
            
        } catch (SQLException ex) {
            //Logger.getLogger(ITagenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestTableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestTableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestTableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestTableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Calendar c = Calendar.getInstance();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TestTableau().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TestTableau.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDroite;
    private javax.swing.JButton btnGauche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
