/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static gestionagenda.GestionAgenda.rq;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Dimension;
import java.awt.HeadlessException;

import com.toedter.calendar.JCalendar;

import database.operationAjout;
import database.operationModif;

import javax.swing.JComboBox;

/**
 *
 * @author Stagiaire
 */
public class ITajoutTypeTache extends javax.swing.JFrame {
	Ioperation Io;
	int id;
    /**
     * Creates new form ITajout
     */
	
	public static ITajoutTypeTache creerFenetre(int id){
		ITajoutTypeTache modif = new ITajoutTypeTache(new operationModif());
		modif.id=id;
		return modif;
	}
	
	public static ITajoutTypeTache creerFenetre(){
		ITajoutTypeTache ajout = new ITajoutTypeTache(new operationAjout());
		ajout.id=0;
		return ajout;
	}
	
    public ITajoutTypeTache(Ioperation Io){
    	this.Io=Io;
    	setMinimumSize(new Dimension(520, 300));
        initComponents();
        
    }
    
    /*
    ============================================================================
    /!\ MANQUE L'AJOUT D'UNE IMAGE DANS LA BD (POSSIBILITE PLUSIEURS ???) /!\
    ============================================================================
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTable = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        labelChoice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbHautGauche = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbHautDroit = new javax.swing.JLabel();
        btnColor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setText("Option Administrateur : Création ");

        labelChoice.setText("Vous pouvez ici créer ");

        lbHautGauche.setText("Nom : ");

        lbHautDroit.setText("Couleur : ");

        btnColor.setText("Choisir la couleur");
        btnColor.setBorderPainted(false);
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        btnCancel.setText("Retourner à l'accueil");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSubmit.setText("Valider la création");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnSubmitActionPerformed(evt);
				} catch (HeadlessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(178)
        							.addComponent(lbTable))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addGap(95)
        									.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lbHautGauche)
        									.addGap(34)
        									.addComponent(txtName, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        									.addGap(5)
        									.addComponent(lbHautDroit)
        									.addPreferredGap(ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
        									.addComponent(btnColor)))
        							.addGap(8)))
        					.addContainerGap())))
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(120)
        					.addComponent(labelTitle))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(labelChoice)))
        			.addContainerGap(179, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(btnSubmit)
        			.addPreferredGap(ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
        			.addComponent(btnCancel)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(labelTitle)
        			.addGap(18)
        			.addComponent(labelChoice)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lbHautGauche)
        						.addComponent(txtName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lbHautDroit)
        						.addComponent(btnColor))
        					.addGap(31)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnSubmit)
        						.addComponent(btnCancel))
        					.addGap(276)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(lbTable))
        			.addPreferredGap(ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
        			.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addGap(38))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Cette fonction sert à quitter l'interface de création.
 * @param evt 
 */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int choice;
        choice = (int)JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment annuler la création ?", "Annuler", JOptionPane.YES_NO_OPTION);
        if(choice == 0){
           this.dispose(); 
        }  
    }//GEN-LAST:event_btnCancelActionPerformed
/**
 * Cette fonction sert à créer la salle ou la tache en question en vérifiant que les différents champs sont remplis.
 * @param evt 
 * @throws SQLException 
 * @throws HeadlessException 
 */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) throws HeadlessException, SQLException {//GEN-FIRST:event_btnSubmitActionPerformed
        //Mettre l'insertion dans la BD + gérer les éventuelles erreurs
        try{
        	if(id!=0){
        	    Io.recevoirId(id);
        	   }
            String nom = txtName.getText();
            
            
            
            if(nom == null || nom.equals("")){
                JOptionPane.showMessageDialog(null, "Veuillez rentrer un nom de "+lbTable.getText());
            }
            else if(this.hex == null){
                JOptionPane.showMessageDialog(null, "Veuillez choisir une couleur pour la "+lbTable.getText());
            }
            else{
                //if(rq.checkErreurModif("typeTache", "nom", nom) && rq.checkErreurModif("typeTache", "codeCouleur", hex)){
                    //if(aire != 0){
                        //rq.ajoutSalle(nom, aire, hex, comment);
                        //JOptionPane.showMessageDialog(null, "Nouvelle salle créée avec succès !");
                        //this.dispose();
                    //}
                    //else{
                    	Io.operationTypeTache(nom, hex);
                        //rq.ajoutTache(nom, hex, comment);
                        JOptionPane.showMessageDialog(null, "Nouvelle tache créée avec succès !");
                        this.dispose();
                    //} 
               // }
                //else{
                  //  JOptionPane.showMessageDialog(null, "Nom de "+lbTable.getText()+" déjà existant ou code couleur déjà utilisé !");
                //}
            }  
            
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tout les champs.");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed
/**
 * Cette fonction sert à choisir une nouvelle couleur et repaint le bouton avec celle-ci.
 * @param evt 
 */
    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        Color couleur = JColorChooser.showDialog(null, "Code couleur de la "+lbTable.getText(), Color.WHITE);
        System.out.println(couleur);
        //Transcription du code couleur RGB en HEX
        if(couleur == null){
        }
        else{
            String hexa = "#"+Integer.toHexString(couleur.getRGB()).substring(2);
            System.out.println("Le hex : "+hexa);
            btnColor.setBackground(couleur);
            this.hex = hexa; 
        }
    }//GEN-LAST:event_btnColorActionPerformed
    
    public static Boolean comparerheures (String horaireDebut, String horaireFin, String dateDebut, String dateFin){
    	String heureDebut=horaireDebut.split(":")[0];
    	String heureFin=horaireFin.split(":")[0];
    	String minDebut=horaireDebut.split(":")[1];
    	String minFin=horaireFin.split(":")[1];
    	if(Integer.parseInt(heureDebut) > Integer.parseInt(heureFin) && dateDebut.equals(dateFin)){
    		 return true;
    	}
    	if(Integer.parseInt(heureDebut) > Integer.parseInt(heureFin) && Integer.parseInt(minDebut) > Integer.parseInt(minFin) && dateDebut.equals(dateFin)){
    		 return true;
    	}
    	return false;
    }
    
    public static Boolean comparerdates (String dateDebut, String dateFin){
    	String jourDebut = dateDebut.split("-")[0];
    	String jourFin = dateFin.split("-")[0];
    	String moisDebut = dateDebut.split("-")[1];
    	String moisFin = dateFin.split("-")[1];
    	String anDebut = dateDebut.split("-")[2];
    	String anFin = dateFin.split("-")[2];
    	if(Integer.parseInt(anFin)<Integer.parseInt(anDebut)){
    		return true;
    	}
    	if(Integer.parseInt(moisFin)<Integer.parseInt(moisDebut) && Integer.parseInt(anFin)==Integer.parseInt(anDebut)){
    		return true;
    	}
    	if(Integer.parseInt(moisFin)==Integer.parseInt(moisDebut) && Integer.parseInt(anFin)==Integer.parseInt(anDebut) && Integer.parseInt(jourFin)<Integer.parseInt(jourDebut)){
    		return true;
    	}
    	return false;
    }

    public String getLabelChoice() {
        return labelChoice.getText();
    }

    public String getLabelTitle() {
        return labelTitle.getText();
    }

    public void setLabelChoice(String labelChoice) {
        this.labelChoice.setText(labelChoice);
    }

    public void setLabelTitle(String labelTitle) {
        this.labelTitle.setText(labelTitle);
    }
    
    public JLabel getLabelTable() {
        return lbTable;
    }

    public void setLabelTable(String labelTable) {
        this.lbTable.setText(labelTable);
    }
    
    public void setCouleur(String couleur){
    	this.hex=couleur;
    	btnColor.setBackground(Color.decode(couleur));
    }
    
    public void setNom(String nom){
    	txtName.setText(nom);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelChoice;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lbHautDroit;
    private javax.swing.JLabel lbHautGauche;
    private javax.swing.JLabel lbTable;
    private javax.swing.JTextField txtName;
    
    // End of variables declaration//GEN-END:variables
    private String hex;
    
}
